// src/router/dashboardRoutes.js
import DashboardLayout from '@/components/dashboard/layout/DashboardLayout.vue'

export default {
  path: '/dashboard',
  component: DashboardLayout,
  meta: { requiresAuth: true },
  children: [

    // ── UMKM ────────────────────────────────────────
    { path: 'umkm',           redirect: { name: 'umkm-overview' } },
    { path: 'umkm/overview',  name: 'umkm-overview',
      component: () => import('@/views/dashboard/umkm/UmkmOverviewView.vue'),
      meta: { title: 'Ringkasan', breadcrumb: 'Ringkasan', role: 'umkm' } },
    { path: 'umkm/profil',    name: 'umkm-profil',
      component: () => import('@/views/dashboard/umkm/ProfilBisnisView.vue'),
      meta: { title: 'Profil Bisnis', breadcrumb: 'Profil Bisnis', role: 'umkm' } },
    { path: 'umkm/keuangan',  name: 'umkm-keuangan',
      component: () => import('@/views/dashboard/umkm/DataKeuanganView.vue'),
      meta: { title: 'Data Keuangan', breadcrumb: 'Data Keuangan', role: 'umkm' } },
    { path: 'umkm/media',     name: 'umkm-media',
      component: () => import('@/views/dashboard/umkm/FotoMediaView.vue'),
      meta: { title: 'Foto & Media', breadcrumb: 'Foto & Media', role: 'umkm' } },
    { path: 'umkm/legalitas', name: 'umkm-legalitas',
      component: () => import('@/views/dashboard/umkm/LegalitasView.vue'),
      meta: { title: 'Legalitas', breadcrumb: 'Legalitas', role: 'umkm' } },
    { path: 'umkm/inbox',     name: 'umkm-inbox',
      component: () => import('@/views/dashboard/umkm/InvestorInboxView.vue'),
      meta: { title: 'Investor Masuk', breadcrumb: 'Investor Masuk', role: 'umkm' } },
    { path: 'umkm/preview',   name: 'umkm-preview',
      component: () => import('@/views/dashboard/umkm/PublicPreviewView.vue'),
      meta: { title: 'Preview Publik', breadcrumb: 'Preview Publik', role: 'umkm' } },

    // ── INVESTOR ─────────────────────────────────────
    { path: 'investor',           redirect: { name: 'inv-overview' } },
    { path: 'investor/overview',  name: 'inv-overview',
      component: () => import('@/views/dashboard/investor/InvestorOverviewView.vue'),
      meta: { title: 'Overview', breadcrumb: 'Overview', role: 'investor' } },
    { path: 'investor/directory', name: 'inv-directory',
      component: () => import('@/views/dashboard/investor/DirectoryView.vue'),
      meta: { title: 'Direktori UMKM', breadcrumb: 'Direktori UMKM', role: 'investor' } },
    { path: 'investor/watchlist', name: 'inv-watchlist',
      component: () => import('@/views/dashboard/investor/WatchlistView.vue'),
      meta: { title: 'Watchlist', breadcrumb: 'Watchlist', role: 'investor' } },
    { path: 'investor/history',   name: 'inv-history',
      component: () => import('@/views/dashboard/investor/RiwayatView.vue'),
      meta: { title: 'Riwayat', breadcrumb: 'Riwayat', role: 'investor' } },
    { path: 'investor/verify',    name: 'inv-verify',
      component: () => import('@/views/dashboard/investor/VerifikasiKtpView.vue'),
      meta: { title: 'Verifikasi KTP', breadcrumb: 'Verifikasi KTP', role: 'investor' } },

    // ── ADMIN ────────────────────────────────────────
    { path: 'admin',              redirect: { name: 'admin-overview' } },
    { path: 'admin/overview',     name: 'admin-overview',
      component: () => import('@/views/dashboard/admin/AdminOverviewView.vue'),
      meta: { title: 'Overview', breadcrumb: 'Overview', role: 'admin' } },
    { path: 'admin/verify',       name: 'admin-verify',
      component: () => import('@/views/dashboard/admin/VerifikasiQueueView.vue'),
      meta: { title: 'Antrian Verifikasi', breadcrumb: 'Antrian Verifikasi', role: 'admin' } },
    { path: 'admin/users',        name: 'admin-users',
      component: () => import('@/views/dashboard/admin/UserManagementView.vue'),
      meta: { title: 'Pengguna', breadcrumb: 'Pengguna', role: 'admin' } },
    { path: 'admin/activity',     name: 'admin-activity',
      component: () => import('@/views/dashboard/admin/ActivityView.vue'),
      meta: { title: 'Aktivitas', breadcrumb: 'Aktivitas', role: 'admin' } },

    // ── PEMERINTAH ───────────────────────────────────
    { path: 'gov',                redirect: { name: 'gov-overview' } },
    { path: 'gov/overview',       name: 'gov-overview',
      component: () => import('@/views/dashboard/gov/GovOverviewView.vue'),
      meta: { title: 'Statistik', breadcrumb: 'Statistik', role: 'pemerintah' } },
    { path: 'gov/heatmap',        name: 'gov-heatmap',
      component: () => import('@/views/dashboard/gov/HeatmapView.vue'),
      meta: { title: 'Peta Sebaran', breadcrumb: 'Peta Sebaran', role: 'pemerintah' } },
    { path: 'gov/sector',         name: 'gov-sector',
      component: () => import('@/views/dashboard/gov/SectorAnalysisView.vue'),
      meta: { title: 'Analisis Sektor', breadcrumb: 'Analisis Sektor', role: 'pemerintah' } },
    { path: 'gov/report',         name: 'gov-report',
      component: () => import('@/views/dashboard/gov/ReportExportView.vue'),
      meta: { title: 'Ekspor Laporan', breadcrumb: 'Ekspor Laporan', role: 'pemerintah' } },

    // ── MENTOR ───────────────────────────────────────
    { path: 'mentor',             redirect: { name: 'mentor-overview' } },
    { path: 'mentor/overview',    name: 'mentor-overview',
      component: () => import('@/views/dashboard/mentor/MentorOverviewView.vue'),
      meta: { title: 'Overview', breadcrumb: 'Overview', role: 'mentor' } },
    { path: 'mentor/umkm',        name: 'mentor-umkm',
      component: () => import('@/views/dashboard/mentor/UmkmBinaanView.vue'),
      meta: { title: 'UMKM Binaan', breadcrumb: 'UMKM Binaan', role: 'mentor' } },
    { path: 'mentor/feedback',    name: 'mentor-feedback',
      component: () => import('@/views/dashboard/mentor/FeedbackView.vue'),
      meta: { title: 'Beri Feedback', breadcrumb: 'Beri Feedback', role: 'mentor' } },
    { path: 'mentor/checklist',   name: 'mentor-checklist',
      component: () => import('@/views/dashboard/mentor/ChecklistView.vue'),
      meta: { title: 'Checklist', breadcrumb: 'Checklist', role: 'mentor' } },
  ],
}